---
title: "06_figures"
author: "Adriana Uscanga"
date: "19/2/2022"
output: html_document
---

# Figures
 
```{r}
# Note: Run 05_analyisis first to have all needed data loaded

# Load packages for making figures:
library(ggplot2)
library(ggpubr)
library(cowplot)
library(rlang)
library(ggsignif)

```

## Figure 2. Structural attributes and tree size contribution to AGB and stem density at plot level

```{r}

# Tree size contribution to stem density

## Data frame for plot 1

p1_df <- plots_cf_4p %>%
  select(plot_id, tree_no, str_class_plots) %>%
  right_join(stems_class_plot, by = "plot_id") %>%
  mutate(stem_prop = stems/tree_no)  %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  mutate(size_class = ifelse(diam_class == "1", "<10",
                             ifelse(diam_class == "2", "10-20",
                                    ifelse(diam_class == "3", "20-30",
                                           ifelse(diam_class == "4", "30-40",
                                                  ifelse(diam_class == "5", "40-50", ">50"))))))
## Stats

### Statistical differences between successional stages within size classes
stat_test <- p1_df %>%
  group_by(diam_class) %>%
  t_test(stem_prop ~ str_class_plots) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

stat_test
stat_test <- stat_test %>%
  add_xy_position(x= "diam_class", dodge = 0.8, group = "str_class_plots") %>% 
  # Change y position of statistical differences
  mutate(y.position = ifelse(diam_class == "1" &
                               group1 == "1" &
                               group2 == "2", 1.0, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "1" &
                               group1 == "1" &
                               group2 == "3", 1.1, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "6" &
                               group1 == "2" &
                               group2 == "3", 0.28, y.position))

### Statistical differences between size classes within successional stages

stat_test2 <- p1_df %>%
  group_by(str_class_plots) %>%
  t_test(stem_prop ~ diam_class) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") 

#### Groupings resulted from stat_test2

c1 <- rep(c(1, 2, 3), each = 6)
c2 <- rep(seq(1, 6), times = 3)
c3 <- list(c("a", "b", "b", "b", "b", "b",
       "a", "b", "c", "d", "d", "d",
       "a", "b", "ac", "cd", "d", "d"))

groupings <- data.frame(c1, c2, c3) 
colnames(groupings) <- c("str_class_plots", "diam_class", "groupings")

groupings <- groupings %>%
  as_tibble() %>%
  arrange(diam_class) %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  mutate(size_class = ifelse(diam_class == "1", "<10",
                             ifelse(diam_class == "2", "10-20",
                                    ifelse(diam_class == "3", "20-30",
                                           ifelse(diam_class == "4", "30-40",
                                                  ifelse(diam_class == "5", "40-50", ">50"))))))

groupings <- groupings %>%
  mutate(x_groupings = c(0.7333333, 1.000000, 1.266667, 1.7333333, 2.000000, 2.266667,
               2.7333333, 3.000000, 3.266667, 3.7333333, 4.000000, 4.266667,
               4.7333333, 5.000000, 5.266667, 5.7333333, 6.000000, 6.266667))

groupings <- groupings %>%
  as_tibble() %>%
  mutate(str_class_plots = as.character(str_class_plots),
         diam_class = as.character(diam_class))

p1_df <- p1_df %>%
  left_join(groupings, by = c("str_class_plots", "diam_class", "succ", "size_class"))

## Plot

p1 <- p1_df %>%
  group_by(succ, diam_class) %>%
  # plot
  ggplot(aes(x = factor(size_class, 
                        levels =c("<10", "10-20", "20-30", "30-40", "40-50", ">50"),
                        ordered = TRUE),
             y = stem_prop)) +
  geom_boxplot(aes(fill = factor(succ,
                           levels = c("VY","Y", "M"),
                           ordered = TRUE)),
             color = "gray25",
               outlier.alpha = 0.5,
               outlier.color = "gray40",
               outlier.size = 1.5) +
  stat_pvalue_manual(stat_test,
                     tip.length = 0.02,
                     hide.ns = T,
                     bracket.size = 0.5) +
  geom_text(aes(x= x_groupings,
                y= -0.05,
                label = groupings,
                color = factor(succ,
                           levels = c("VY","Y", "M"),
                           ordered = TRUE)),
                size = 3) +
  scale_color_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  scale_fill_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  scale_y_continuous(breaks = c(0.0, 0.25, 0.50, 0.75, 1.0)) +
  theme_classic() +
  labs(x = "Size class",
       y = "Proportion of stems") +
  theme(axis.title.x = element_text(size = 10)) +
  theme(axis.title.y = element_text(size = 9)) +
  theme(axis.text = element_text(size = 8)) +
  theme(legend.position = "none") +
  theme(plot.margin = margin(b= 10, t= 9))


# Tree size contribution to AGB

## Data frame for plot 1

p2_df <- plots_cf_4p %>%
  select(plot_id, agb_plot, str_class_plots) %>%
  right_join(agb_class_plots, by = "plot_id") %>%
  mutate(agb_prop = agb_class_plot/agb_plot)  %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  mutate(size_class = ifelse(diam_class == "1", "<10",
                             ifelse(diam_class == "2", "10-20",
                                    ifelse(diam_class == "3", "20-30",
                                           ifelse(diam_class == "4", "30-40",
                                                  ifelse(diam_class == "5", "40-50", ">50"))))))

## Stats

### Statistical differences between successional stages within size classes
stat_test_p2 <- p2_df %>%
  group_by(diam_class) %>%
  t_test(agb_prop ~ str_class_plots) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

stat_test_p2

stat_test_p2 <- stat_test_p2 %>%
  add_xy_position(x= "diam_class", dodge = 0.8, group = "str_class_plots") %>% 
  #Change y position of statistical differences
  mutate(y.position = ifelse(diam_class == "1" &
                               group1 == "1" &
                               group2 == "3", 0.90, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "1" &
                               group1 == "2" &
                               group2 == "3", 1.0, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "2" &
                              group1 == "1" &
                              group2 == "3", 1.1, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "2" &
                              group1 == "2" &
                              group2 == "3", 1.2, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "3" &
                              group1 == "1" &
                              group2 == "3", 1.1, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "3" &
                              group1 == "2" &
                              group2 == "3", 1.2, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "4" &
                              group1 == "1" &
                              group2 == "2", 1.1, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "4" &
                              group1 == "1" &
                              group2 == "3", 1.2, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "5" &
                              group1 == "1" &
                              group2 == "2", 1.05, y.position)) %>%
  mutate(y.position = ifelse(diam_class == "5" &
                              group1 == "1" &
                              group2 == "3", 1.15, y.position))

### Statistical differences between size classes within successional stages

stat_test2_p2 <- p2_df %>%
  group_by(str_class_plots) %>%
  t_test(agb_prop ~ diam_class) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

#### Groupings resulted from stat_test2_p2

c1 <- rep(c(1, 2, 3), each = 6)
c2 <- rep(seq(1, 6), times = 3)
c3 <- list(c("a", "b", "b", "bc", "c", "abc",
       "a", "b", "b", "b", "b", "b",
       "a", "b", "bc", "bcd", "cd", "e"))

groupings2 <- data.frame(c1, c2, c3) 
colnames(groupings2) <- c("str_class_plots", "diam_class", "groupings")

groupings2 <- groupings2 %>%
  as_tibble() %>%
  arrange(diam_class) %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  mutate(size_class = ifelse(diam_class == "1", "<10",
                             ifelse(diam_class == "2", "10-20",
                                    ifelse(diam_class == "3", "20-30",
                                           ifelse(diam_class == "4", "30-40",
                                                  ifelse(diam_class == "5", "40-50", ">50"))))))

groupings2 <- groupings2 %>%
  mutate(x_groupings = c(0.7333333, 1.000000, 1.266667, 1.7333333, 2.000000, 2.266667,
               2.7333333, 3.000000, 3.266667, 3.7333333, 4.000000, 4.266667,
               4.7333333, 5.000000, 5.266667, 5.7333333, 6.000000, 6.266667))

groupings2 <- groupings2 %>%
  as_tibble() %>%
  mutate(str_class_plots = as.character(str_class_plots),
         diam_class = as.character(diam_class))

p2_df <- p2_df %>%
  left_join(groupings2, by = c("str_class_plots", "diam_class", "succ", "size_class"))


## Plot
p2 <-  p2_df %>%
  group_by(str_class_plots, diam_class) %>%
  ggplot(aes(x = factor(size_class, 
                        levels =c("<10", "10-20", "20-30", "30-40", "40-50", ">50"),
                        ordered = TRUE),
             y = agb_prop)) +
  geom_boxplot(aes(fill = factor(succ,
                           levels = c("VY","Y", "M"),
                           ordered = TRUE)),
             color = "gray25",
               outlier.alpha = 0.5,
               outlier.color = "gray40",
               outlier.size = 1.5) +
  stat_pvalue_manual(stat_test_p2,
                     tip.length = 0.02,
                     hide.ns = T,
                     bracket.size = 0.5,
                     step.increase = 0.001,
                     bracket.nudge.y = -0.015,
                     bracket.shorten = -0.05) +
  geom_text(aes(x= x_groupings,
                y= -0.05,
                label = groupings,
                color = factor(succ,
                           levels = c("VY","Y", "M"),
                           ordered = TRUE)),
                size = 3) +
  scale_color_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  scale_fill_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  theme_classic() +
  scale_y_continuous(breaks = c(0.0, 0.25, 0.50, 0.75, 1.0)) +
  labs(x = "Size class",
       y = "Proportion of AGB") +
  theme(axis.title.x = element_text(size = 10)) +
  theme(axis.title.y = element_text(size = 9)) +
  theme(axis.text = element_text(size = 8)) +
  theme(legend.position = "none") +
  theme(plot.margin = margin(b= 10, t= 9))
p1
p2  
   

# Structural attributes across succesional stages

p3 <- plots_cf_4p %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  ggplot(aes(x= factor(succ, levels = c("VY","Y", "M"),ordered = TRUE), y = tree_density, fill = factor(succ, levels = c("VY","Y", "M"),ordered = TRUE))) +
  geom_boxplot(color = "gray25",
               outlier.alpha = 0.5,
               outlier.color = "gray40",
               outlier.size = 1.2) +
  theme_classic() +
  scale_fill_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  theme(axis.title.x = element_blank()) +
  labs(y = "Stem density (tree/ha)") +
  theme(axis.title.y = element_text(size = 9)) +
  theme(axis.text = element_text(size = 8)) +
  theme(legend.position = "none") +
  theme(plot.margin = margin(t= 5))

p4 <- plots_cf_4p %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  ggplot(aes(x= factor(succ, levels = c("VY","Y", "M"),ordered = TRUE), y = loreys_height, fill = factor(succ, levels = c("VY","Y", "M"),ordered = TRUE))) +
  geom_boxplot(color = "gray25",
               outlier.alpha = 0.5,
               outlier.color = "gray40",
               outlier.size = 1.2) +
  theme_classic() +
  scale_fill_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  theme(axis.title.x = element_blank()) +
  labs(y = "Lorey's height (m)") +
  theme(axis.title.y = element_text(size = 9)) +
  theme(axis.text = element_text(size = 8)) +
  theme(legend.position = "none") +
  theme(plot.margin = margin(t= 5))

p5 <- plots_cf_4p %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  ggplot(aes(x= factor(succ, levels = c("VY","Y", "M"),ordered = TRUE), y = basal_area_ha, fill = factor(succ, levels = c("VY","Y", "M"),ordered = TRUE))) +
  geom_boxplot(color = "gray25",
               outlier.alpha = 0.5,
               outlier.color = "gray40",
               outlier.size = 1.2) +
  theme_classic() +
  scale_fill_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  theme(axis.title.x = element_blank()) +
  labs(y = "Basal area (m/ha)") +
  theme(axis.title.y = element_text(size = 9)) +
  theme(axis.text = element_text(size = 8)) +
  theme(legend.position = "none") +
  theme(plot.margin = margin(t= 5))

comp <- list(c("VY","Y"), c("VY","M"), c("Y","M"))
p6 <- plots_cf_4p %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  ggplot(aes(x= factor(succ, levels = c("VY","Y", "M"),ordered = TRUE), y = agb_plot_ha, fill = factor(succ, levels = c("VY","Y", "M"),ordered = TRUE))) +
  geom_boxplot(color = "gray25",
               outlier.alpha = 0.5,
               outlier.color = "gray40",
               outlier.size = 1.2) +
  stat_compare_means(comparisons = comp,
                     label = "p.signif") +
  theme_classic() +
  scale_fill_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  theme(axis.title.x = element_blank()) +
  labs(y = "AGB (Mg/ha)") +
  theme(axis.title.y = element_text(size = 9)) +
  theme(axis.text = element_text(size = 8)) +
  theme(legend.justification = "bottom") +
  theme(plot.margin = margin(t= 5))
p6

p6b <- p6 + theme(legend.position = "none") 

legend <- get_legend(p6)

row1 <- plot_grid(p1, p2,
                  labels = c("a)", "b)"),
                  label_size = 8,
                  hjust = -1)

row2 <- plot_grid(p3,p4,p5,p6b,
                  ncol = 4,
                  nrow = 1,
                  label_size = 8, labels = c("c)", "d)", "e)", "f)"),
                  vjust = 1,
                  hjust = -1,
                  rel_widths = c(1,1,1,1))

figure2 <- ggarrange(row1, row2, legend,
                     nrow = 3,
                     heights = c(2, 1, 0.2),
                     common.legend = T)
figure2

# add significance
# add legend
```

## Figure 3. Relationship between AGB and landscape composition, and diversity and landscape composition

```{r}

# AGB ~ landscape composition

p1 <- sites_cf_4p %>%
  ggplot(aes(x = landscape, y = av_agb_site)) +
  geom_smooth(method = "lm", color = "gray30", se = F, linetype = "dashed") +
  geom_smooth(method = "loess", span=1, color = "gray80", se = F, linetype = "dashed") +
  geom_point(color = "black", size = 2) +
  theme_classic() +
  labs(x = "Landscape composition",
       y = "AGB (Mg/ha)")

# Tree diversity ~ landscape composition

p2 <- sites_cf_4p %>%
  ggplot(aes(x = landscape, y = shannon_av_site)) +
  geom_smooth(method = "lm", color = "gray30", se = F, linetype = "dashed") +
  geom_smooth(method = "loess", span=1, color = "gray80", se = F, linetype = "dashed") +
  geom_point(color = "black", size = 2) +
  theme_classic() +
  labs(x = "Landscape composition",
       y = "H")

figure3 <- plot_grid(p1, p2,
          labels = c("a)", "b)"),
          label_size = 10,
          hjust = -1)

figure3
```

## Figure 4.  Regressions between AGB and env_pc1 and landscape composition and env_pc1

```{r}

# AGB ~ env_pc1

p1 <- ggplot(sites_cf_4p, aes(x = env_pc1, y = av_agb_site)) +
  geom_smooth(alpha= 0.1, method = "lm", color = "darkgray", linetype = "dashed") +
  geom_point(aes(color = landscape), size = 4) +
  scale_color_gradient(low = "forestgreen", high =  "lightgoldenrod2") +
  theme_classic() +
  labs(x = "Environmental gradient",
       y = "AGB (Mg/ha)",
       color = "Landscape \ncomposition   ") +
  theme(legend.position='top', 
        legend.justification='right',
        legend.direction='horizontal',
        legend.key.height = unit(0.25, "cm"),
        legend.key.width = unit(0.75, "cm"),
        legend.text = element_text(size= 8),
        legend.title = element_text(size = 9),
        legend.title.align = 0)


# Landscape composition ~ env_pc1

p2 <- ggplot(sites_cf_4p, aes(x = env_pc1, y = landscape)) +
  geom_smooth(alpha= 0.1, method = "lm", color = "darkgray", linetype = "dashed") +
  geom_point(aes(color = av_agb_site), size = 4) +
  scale_color_gradient(high = "darkgreen", low = "darkseagreen1") +
  theme_classic() +
  labs(x = "Environmental gradient",
       y = "Landscape composition",
       color = "AGB (Mg/ha)") +
  scale_y_continuous(limits = c(0.0, 1.0), breaks = c(0.0, 0.25, 0.50, 0.75, 1.00)) +
  theme(legend.position='top', 
        legend.justification='right',
        legend.direction='horizontal',
        legend.key.height = unit(0.25, "cm"),
        legend.key.width = unit(0.75, "cm"),
        legend.text = element_text(size= 8),
        legend.title = element_text(size = 9),
        legend.title.align = 0)

figure4 <- plot_grid(p1, p2,
          labels = c("a)", "b)"),
          label_size = 10,
          hjust = -1)

figure4
```

# Figure 5. Loess curves of AGB and tree diversity at site and plot levels

```{r}

# Sites

## Shannon

sites_cf_4p %>%
  ggplot(aes(x = av_agb_site, y = shannon_av_site)) +
  geom_smooth(alpha = 0.1, method = "loess", span = 1, color= "gray75", linetype = "dashed") +
  geom_point(size=2) +
  theme_classic() +
  labs(x = "AGB (Mg/ha)",
       y = "H")

## Sp richness

sites_cf_4p %>%
  ggplot(aes(x = av_agb_site, y = sp_richness_site_av)) +
  geom_smooth(alpha = 0.1, method = "loess", span = 1, color= "gray75", linetype = "dashed") +
  geom_point(size=2) +
  theme_classic() +
  labs(x= "AGB (Mg/ha)",
       y= "S")

# Plots

## Shannon 

plots_cf_4p %>%
  filter(agb_plot_ha < 600) %>%
  filter(!is.na(shannon)) %>%
  filter(!is.na(agb_plot_ha)) %>%
  group_by(str_class_plots) %>%
  summarise(mean_shannon = mean(shannon),
            mean_agb = mean(agb_plot_ha),
            agb_plot_ha = as.numeric(agb_plot_ha),
            shannon = as.numeric(shannon)) %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  ggplot(aes(x = agb_plot_ha, y = shannon)) +
  #geom_point(aes(x= mean_agb, y = mean_shannon, color = factor(succ, levels = c("VY","Y", "M"),ordered = TRUE), size = 3)) +
  geom_point(aes(color = factor(succ, levels = c("VY","Y", "M"),ordered = TRUE)), size= 2, alpha = 0.75) +
  geom_smooth(alpha = 0.15, method = "loess", span = 1, color= "gray75", linetype = "dashed") +
  theme_classic() +
  scale_color_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  labs(color = "Successional Stage",
       size = "Average H in successional stage",
       x = "AGB (Mg/ha)",
       y = "H")

## Species richness

plots_cf_4p %>%
  filter(agb_plot_ha < 600) %>%
  filter(!is.na(simpson)) %>%
  filter(!is.na(agb_plot_ha)) %>%
  group_by(str_class_plots) %>%
  summarise(mean_sp = mean(sp_richness_plot),
            mean_agb = mean(agb_plot_ha),
            agb_plot_ha = as.numeric(agb_plot_ha),
            sp_richness_plot = as.numeric(sp_richness_plot)) %>%
  mutate(succ = ifelse(str_class_plots == "1", "VY",
                       ifelse(str_class_plots == "2", "Y", "M"))) %>%
  ggplot(aes(x = agb_plot_ha,
             y = sp_richness_plot,
             color = factor(succ, levels = c("VY","Y", "M"), ordered = TRUE))) +
  geom_point(aes(color = factor(succ, levels = c("VY","Y", "M"), ordered = TRUE)), size= 2, alpha = 0.75) +
  geom_smooth(alpha = 0.15, method = "loess", span = 1, color= "gray75", linetype = "dashed") +
  theme_classic() +
  scale_color_manual(values = c("#d95f02", "#7570b3", "#1b9e77")) +
  labs(color = "Successional Stage",
       size = "Average H in successional stage",
       x = "AGB (Mg/ha)",
       y = "S")


```

